# .bash_profile

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
	source ~/.bashrc
fi

# User specific environment and startup programs

# FIXME remove_path_duplicates

if [ "$(type -t add_to_path)" = "function" ]; then
    if [ -x /usr/bin/rpm ]; then
        # GLIBC_VERSION=$(rpm -q --provides glibc | grep 'libc.so.6(GLIBC_2.[34][0-9])' | sed -e 's/libc.so.6(\(.*\))(64bit)/\1/')
        CURRENTGLIBC=$(rpm -q --provides glibc | grep 'libc.so.6(GLIBC_2.43)') # F44+
    fi
    if [ -n "$CURRENTGLIBC" ]; then
        add_to_path $HOME/.local/bin before
        add_to_path $HOME/bin before
        add_to_path $HOME/.cargo/bin
    else
        add_to_path $HOME/bin before
        add_to_path $HOME/.cargo/bin
        remove_from_PATH $HOME/.local/bin
        add_to_path $HOME/.local/bin
    fi
    #:$HOME/.local/share/coursier/bin
    #add_to_path "$HOME/.elan/bin" before
    export PATH
fi

#NPM_PACKAGES="${HOME}/.npm-packages"
#PATH="$PATH:$NPM_PACKAGES/bin"

export PANGO_LANGUAGE=ja

export VIRSH_DEFAULT_CONNECT_URI=qemu:///system

export DARCS_PAGER=cat

export TMPDIR=$HOME/tmp

export NPM_CONFIG_PREFIX=~/.npm-global

export GIT_PAGER=cat

NAME=${NAME:+Jens Petersen}

export EDITOR=vi
