#!/usr/bin/bash

# .bashrc

OLDHOME=$HOME
HOME=$(readlink -e $HOME)
if [ "$HOME" != "$OLDHOME" ]; then
    echo "OLDHOME: $OLDHOME"
else
    unset OLDHOME
fi

# Source global definitions
if [ -f /etc/bashrc ]; then
    source /etc/bashrc
fi

remove_from_PATH() {
    PATH=$(echo $PATH | sed -e s"%$1:%%" -e s"%:$1$%%")
}

add_to_path() {
    [ ! -d "$1" ] && return

    case ":${PATH}:" in
        *:"$1":*)
            ;;
        *)
            if [ "$2" = "before" ] ; then
                PATH=$1:$PATH
            else
                PATH=$PATH:$1
            fi
    esac
}

# exit if non-interactive (no stdin)
[ ! -t 0 ] && return 0

############### below is for interactive shell only ###########################

# if [ "${-#*i}" != "$-" ]; then
#     echo -e "default prompt: ${PS1@P}"
# fi

eval $(grep "\(^ID=\|VERSION_ID\|VARIANT_ID\|ANSI_COLOR\)" /etc/os-release)

if [ -n "$container" ]; then
export HISTFILE="${HOME}/.bash_history.tb.${ID}${VERSION_ID}.${TERM}"
fi

## avoid systemctl auto-paging
# export SYSTEMD_PAGER=

# dont cache command locations
set +h

# User specific aliases and functions
alias ls='ls --color=auto'

vterm_printf(){
    if [ -n "$TMUX" ] && ([ "${TERM%%-*}" = "tmux" ] || [ "${TERM%%-*}" = "screen" ] ); then
        # Tell tmux to pass the escape sequences through
        printf "\ePtmux;\e\e]%s\007\e\\" "$1"
    elif [ "${TERM%%-*}" = "screen" ]; then
        # GNU screen (screen, screen-256color, screen-256color-bce)
        printf "\eP\e]%s\007\e\\" "$1"
    else
        printf "\e]%s\e\\" "$1"
    fi
}

# for prompt and directory tracking
# was "51;A$(whoami)@$(hostname):$(pwd)"
emacs_term_send_dir(){
    case "$INSIDE_EMACS" in
        vterm) vterm_printf "51;A$PWD" ;;
        *,eat) vterm_printf "51;e;A;$(echo "$PWD" | base64)" ;;
    esac
}

# Bash Color Prompt
source ~/src/bash-color-prompt2/bash-color-prompt.sh

#bcp_os_release ANSI_COLOR

bcp_layout() {
    local exit_code=$1

    bcp_duration 1 "yellow" "took "  "\n"
    bcp_append "\t \D{%b %-d (%a)}\n" "dim;reverse"

    local host=""
    if [ -n "$container" ]; then
        case "$VARIANT_ID" in
            eln)
                host="$VARIANT_ID" ;;
            *)
                host="$ID$VERSION_ID" ;;
        esac
        bcp_append "⬢$host" "$ANSI_COLOR;7;107"
    fi
    # if INSIDE_EMACS toolbox ignore lvl 2
    # and/or show shell
    bcp_shlvl "bgmagenta"

    bcp_append "\w" "yellow;7;1"

    ## already done by vte.sh
    # bcp_title "\u@\h"

    bcp_git_branch "bgmagenta;white" "yellow;bgmagenta"

    emacs_term_send_dir

    if [[ $exit_code -ne 0 ]]; then
        bcp_append " ✘$exit_code" "red;bold"
    fi

    bcp_append "\$ " "default"
}

bcp_init

# PROMPT_END='${branch@P}\[$(emacs_term_prompt_end)\]'"\[$COL_RESET\]"

## only for legacy nix
# if [ -n "$IN_NIX_SHELL" ]; then
#     echo $IN_NIX_SHELL
#     PROMPT_CONTAINER="❄️$PROMPT_CONTAINER"
# fi

if [ -x "/usr/bin/zoxide" ]; then
    eval "$(zoxide init bash)"
fi
