# .bash_profile

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
	source ~/.bashrc
fi

# User specific environment and startup programs

CURRENTGLIBC=$(rpm -q --provides glibc | grep 2.38) # F39+
if [ -n "$CURRENTGLIBC" ]; then
    export PATH=$HOME/bin:$HOME/.local/bin:$PATH:$HOME/.cabal/bin:$HOME/.cargo/bin
else
    export PATH=$HOME/bin:$PATH:$HOME/.cabal/bin:$HOME/.cargo/bin:$HOME/.local/bin
fi
#:$HOME/.local/share/coursier/bin

#NPM_PACKAGES="${HOME}/.npm-packages"
#PATH="$PATH:$NPM_PACKAGES/bin"

export PANGO_LANGUAGE=ja

export VIRSH_DEFAULT_CONNECT_URI=qemu:///system

export DARCS_PAGER=cat

export TMPDIR=$HOME/tmp

export NPM_CONFIG_PREFIX=~/.npm-global

export GIT_PAGER=cat

NAME=${NAME:+Jens Petersen}

export EDITOR=vi
